name: Validate links

on: pull_request
#on: 
#  schedule:
#    # At 09:00 on Monday: https://crontab.guru/#0_9_*_*_1
#    - cron:  '0 9 * * 1'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
        
    - name: Install awesome_bot
      run: gem install awesome_bot
        
    - name: Check links
      id: awesome_bot
      run: |
        echo ::set-output name=check_links::$(awesome_bot README.md)
        
    - name: Create issue if awesome_bot fails
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BODY: ${{ steps.awesome_bot.outputs.check_links }}
      with:
        filename: .github/ISSUE_TEMPLATE/custom.md
        update_existing: true
